apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: utxj-workshop-ricardo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: utxj-workshop-api
    newName: ghcr.io/nochebuenadev/utxj-workshop-api
    newTag: main-877568f
